global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["host.docker.internal:3001"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
